appName: "chat_room"

mysql:
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  database: "go_chat"
  tablePrefix: "chat_"

redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0

msgChannelType:
  channelType : "gochannel"
  kafkaHost: "kafka:9092"
  kafkaTopic: "chat_room"

staticPath:
  filePath : "web/static/file/"