appName: "gochat"

mysql:
  host: mysql
  port: 3306
  username: "root"
  password: "123456"
  database: "go_chat"
  tablePrefix: "chat_"

redis:
    host: mysql
    port: 6379
    password: ""
    db: 0

msgChannel:
  channelType : "gochannel"
  kafkaHost: "kafka:9092"
  kafkaTopic: "chat_room"

path:
  filePath : "web/static/file/"